name: embedded_control
description: Interface de contrôle pour système électronique embarqué avec GSM/GPRS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1

  fl_chart: ^0.66.0
  animated_toggle_switch: ^0.8.2
  flutter_animate: ^4.3.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  percent_indicator: ^4.2.3
  mqtt_client: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
